sample_sheet: ".test/config/samples.tsv"

# You have to manually download and extract the reference
# data that you need and provide the path where you extracted
# this to right here. Usually, the folder after extraction
# will be named something like: refdata-gex-GRCh38-2024-A/
ref_data: "/absolute/path/to/ref_data/folder/refdata-gex-GRCh38-2024-A/"
