name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Formatting
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_YAML_PRETTIER: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Formatting
      - Linting
    steps:
      - uses: actions/checkout@v4

      - name: Test multi_lane_sample workflow dryrun
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .test/
          snakefile: .test/Snakefile
          stagein: 'export CELLRANGER_TARBALL="fake_this_absolute_path"'
          args: >
            --sdm conda --conda-cleanup-pkgs cache --all-temp
            --show-failed-logs --cores 2
            --dryrun

      - name: Test no_lane_sample workflow dryrun
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .test/
          snakefile: .test/Snakefile
          stagein: 'export CELLRANGER_TARBALL="fake_this_absolute_path"'
          args: >
            --configfile .test/config/config_no_lane.yaml
            --sdm conda --conda-cleanup-pkgs cache --all-temp
            --show-failed-logs --cores 2
            --dryrun

      - name: Test multi_lane_sample workflow without cellranger
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .test/
          snakefile: .test/Snakefile
          stagein: 'export CELLRANGER_TARBALL="fake_this_absolute_path"'
          args: >
            create_cellranger_library_csv
            --sdm conda --conda-cleanup-pkgs cache --all-temp
            --show-failed-logs --cores 2

      - name: Test no_lane_sample workflow without cellranger
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: .test/
          snakefile: .test/Snakefile
          stagein: 'export CELLRANGER_TARBALL="fake_this_absolute_path"'
          args: >
            create_cellranger_library_csv
            --configfile .test/config/config_no_lane.yaml
            --sdm conda --conda-cleanup-pkgs cache --all-temp
            --show-failed-logs --cores 2
